#PBS -S /bin/bash
### General Options ###
#PBS -N BCN-MD
#PBS -V
### Resource Handling ###
#PBS -l nodes=1:ppn=25
#PBS -q GPU
#PBS -l walltime=100:00:00
### Output Stream Options ###
### Mail Options ###
#PBS -m bea
 
### Bash script ###
cd /home/98722002/Desktop/WORK-DIRECTORY/BCN/02_step1_cp2k-MD/BCN-MD
source /home/98722002/cp2k-v7/cp2k-7.1.0/tools/toolchain/install/setup

python e-h-recom_res.py > out_e-h-recom_c3n4.log


exit 0
